;;; avy-jump-helm-line-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from avy-jump-helm-line.el

(autoload 'avy-jump-helm-line "avy-jump-helm-line" "\
Jump to a candidate and execute the default action." t)
(autoload 'avy-jump-helm-line-and-select "avy-jump-helm-line" "\
Jump to and select the candidate in helm window." t)
(defalias 'avy-jump-helm-line-execute-action 'avy-jump-helm-line-and-select)
(autoload 'avy-jump-helm-line-idle-exec-add "avy-jump-helm-line" "\


(fn FUNC)")
(autoload 'avy-jump-helm-line-idle-exec-remove "avy-jump-helm-line" "\


(fn FUNC)")
(register-definition-prefixes "avy-jump-helm-line" '("avy-jump-helm-line-"))

;;; End of scraped data

(provide 'avy-jump-helm-line-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; avy-jump-helm-line-autoloads.el ends here
